# Generated by Django 5.1.5 on 2025-01-22 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=255)),
                ('mobile_no', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('profession', models.CharField(max_length=255)),
                ('referred_by', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diabetes', models.BooleanField(default=False)),
                ('tuberculosis', models.BooleanField(default=False)),
                ('high_blood_pressure', models.BooleanField(default=False)),
                ('hepatitis', models.BooleanField(default=False)),
                ('rheumatic_fever', models.BooleanField(default=False)),
                ('excessive_bleeding', models.BooleanField(default=False)),
                ('heart_trouble', models.BooleanField(default=False)),
                ('allergies', models.TextField(blank=True)),
                ('other_medical_problems', models.TextField(blank=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
            ],
        ),
        migrations.CreateModel(
            name='DentalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_dental_exam', models.DateField(blank=True, null=True)),
                ('last_dental_xray', models.DateField(blank=True, null=True)),
                ('physicians_name', models.CharField(blank=True, max_length=255)),
                ('current_medications', models.TextField(blank=True)),
                ('pregnant', models.BooleanField(default=False)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateField()),
                ('procedure', models.TextField()),
                ('comments', models.TextField(blank=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
            ],
        ),
    ]
