# Generated by Django 5.1.5 on 2025-01-25 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalhistory',
            name='patient',
        ),
        migrations.AddField(
            model_name='patient',
            name='allergies',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='dental_concerns',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='diabetes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='discomfort_of_pain',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='excessive_bleeding',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='heart_trouble',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='hepatitis',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='hepatitis_type',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='patient',
            name='high_blood_pressure',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='is_pregnant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='last_dental_exam',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='last_dental_xray',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='medications',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='other_medical_problems',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='physician_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='patient',
            name='rheumatic_fever',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='tuberculosis',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='DentalHistory',
        ),
        migrations.DeleteModel(
            name='MedicalHistory',
        ),
    ]
