# Generated by Django 5.1.5 on 2025-01-25 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_remove_medicalhistory_patient_patient_allergies_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='guardian_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
