# Generated by Django 5.1.5 on 2025-01-27 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_patient_entry_date_alter_patient_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedure',
            name='description',
            field=models.TextField(),
        ),
    ]
